### ISSUE TITLE
Large Log File on Merge

### ISSUE THREAD

**Issue by stsmall** [jydu/maffilter#2]
Hi @jydu,
I am having issues when I use the Merge function where my log file (output.log) gets to a size of >1Tb. This is because every time a block is merged the CHROMOSOME identifier is also extended with "-". The log file records when each sequence is merged printing out the entire chromosome string for each individual which can get very long.
I tried to suppress the output.log, by output.log=none or output.log='', but maffilter returns an error "You must specify a file for this parameter: output.log"
Any ideas?
thank you,
@stsmall

**Comment by jydu** [comment]
Hi,

Yes, currently working on a fix to have the "none" option recognised. Also adding an option to automatically rename the merged contigs to avoid long concatenated names. Should be ready beginning of next week!

Thanks for reporting this,

Julien.

**Comment by jydu** [comment]
Should be fixed now. Available when compiling from the master branch (requires Bio++ libraries from the github repository too), and will be included in next release (should come in the next two weeks or so). Merge filter has a new option rename_chimeric_contigs which, when set to yes, will set a new "chromosome" name instead of concatenating the input ones.

J.

**Comment by stsmall** [comment]
Thanks!
I did find that MafFilter did not recognize "rename_chimeric_contigs" but instead the option is "rename_chimeric_chromosomes"

**Comment by jydu** [comment]
Indeed, my mistake!
