### ISSUE TITLE
How to convert maf file into msmc input file for reference species 

### ISSUE THREAD

**Issue by aaannaw** [jydu/maffilter#30]
Hello
I am running Maffilter to convert a maf file into msmc input file. The maf file was a multiple alignment file for 13 genomes of 13 species , which was generated by cactus software. Now I want to estimate effective population size and population separation history for every species (note each species only have one genome). For each query species, I respectively run Maffilter with the following config file:
```
input.file=13.noanc.filter.allspecies.150bp.maf
input.format=Maf
input.file.compression=none
output.log=Fan.msmsc.log
maf.filter = MsmcOutput(                             \
        file=Fan.out.msmc,                      \
        compression=none,                   \
        reference=Bsu,                      \
        genotypes=(Bsu,Fan)),
```
Note: Bsu is the reference file and Fan is one of query species.
However, I have no idea how to get msmc input file for reference species (Bsu).
Could you give me any suggestions.
Best wishes!
Na Wan

**Comment by jydu** [comment]
Dear Na Wan,

To run MSMC, you need at least two haploid genomes (one diploid) from one species. MAF files are originally meant for inter-species alignments, so that each entry corresponds to one consensus genome per species. You can use MAF files to store multiple individual genomes though, as haploid genomes. You can then convert the output to MSMC input format, you then need to provide their names in the 'genotypes' arguments: genotypes = (indv1_haplotype1,indv2_haplotype2). You cannot run MSMC with two genomes from different species (well, you technically can, but the model is not meant for that).

I hope this helps,

Julien.

**Comment by aaannaw** [comment]
Hello, Julien
Thanks for your reply. I understand your meaning. However, in the maf file, there is only one haploid genome from one sample for each species. Thus, I can not estimate population history for every species via converting the maf file into msmsc input  format.  
Thanks again for your reply!
Best wishes!
Na Wan

**Comment by jydu** [comment]
Indeed, in that case, you cannot run MSMC!
